@startuml
participant main
participant laby as "laby : Labyrinthe"
participant pj as "pj : Perso"
main -> laby : deplacerPerso(GAUCHE)
activate laby
laby -> laby : getSuivant(courante[0], courante[1], GAUCHE)
activate laby
laby --> laby : suivante
deactivate laby
laby -> pj : x = suivante[0] y = suivante[1]
activate pj
pj --> laby
deactivate pj
laby --> main
@enduml