@startuml

abstract class Deplacable{
+dx : int
+dy : int
+getX() : int
+getY() : int
+etrePresent(dx : int, dy : int) : boolean
+{abstract}deplacer(dx : int, dy : int)
+{abstract}collision(objet : Deplacable)
}



class Perso{
+Perso(dx : int, dy : int)
+infligerDegats(v : Vivant)
}

class Monstre{
+Monstre(dx : int, dy : int)
+infligerDegats(v : Vivant)
}

abstract class Vivant{
+{abstract}infligerDegats(v : Vivant)
+subirDegats(degats : int)
}

interface Victime {
+subirDegats(degats : int)
}

abstract class Attaque {
+{abstract}infligerDegats(v : Vivant)
+collision(objet : Deplacable)
}

class Fleche {
+deplacer(dx : int, dy : int)
}

abstract class Ennemi {
}

Deplacable <|-- Fleche
Deplacable <|-- Vivant
Perso --|> Vivant
Monstre --|> Ennemi
Ennemi --|> Vivant
Vivant ..|> Victime
Vivant --|> Attaque
Fleche --|> Attaque
@enduml